apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: default       # or whatever namespace you are using
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
