apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: default
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP
