apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: default   # Change if using a different namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: product-service:latest  # Must match your Docker image
          ports:
            - containerPort: 5001
